# -------------------- SEQUENCES / PLAYBOOKS --------------------
sequences:
  - name: Open_To_Lunch_RiskOff
    profile: linear_15m
    steps:
      - t: 0m
        include:
          - Opening_Auction_Gap_40bps

      - t: 3m
        include:
          - RiskOff_Equity_-10

      - t: 5m
        include:
          - Spread_2x_Depth_-30
          - Venue_Latency_p99_+80ms

      - t: 12m
        include:
          - IV_Surge_30

  - name: Bank_Run_Day1
    profile: easing_1h
    steps:
      - t: 0m
        include:
          - Deposit_Run_10pct

      - t: 15m
        include:
          - Network_Congestion_x2

      - t: 30m
        include:
          - Credit_Widen_300